### ISSUE TITLE
Need more robust user API

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#102]
API should return all data needed for a landing page (see screenshot here: https://github.com/gitsubmit/gitsubmit.github.io/pull/20 )

**Comment by sonph** [comment]
The response ideally should contain these information:
- classes that the current user is enrolled in; for each class
  - id
  - name
  - teacher's name
- projects that the current user is involved in; for each project:
  - class id
  - project id
  - due date
- submissions that the current user is involved in; for each submission:
  - username (primary contributor), may not be the current user
  - submission id
  - project name

Something like this:
```
{
    "classes": [{"class_id": "", "class_name": "", "prof_name": ""}, ...],
    "projects": [{"class_id": "", "project_id": "", "due_date": ""}, ...],
    "submissions": [{"username": "", "submission_id": "", "project": ""}, ...]
}
```
