### ISSUE TITLE
Tie Classes page into API

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#105]

**Comment by shawkinsl** [comment]
Clarification: this should just be a listing of all classes ( http://api.gitsubmit.com:5123/job/acceptance-tests/335/robot/report/log.html#s1-s1-s1-s1-t1-k3-k1 )

**Comment by sonph** [comment]
So this issue is about creating front end url `/classes` to show the list of classes. Am I correct?

**Comment by shawkinsl** [comment]
Yep!
