### ISSUE TITLE
Need user creation html

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#12]
See GitHub for inspiration.

Consider buttons for OAuth?

**Comment by shawkinsl** [comment]
Any updates on these? Please remember to open pull requests against the new frontend repo (https://github.com/gitsubmit/gitsubmit.github.io). They may also depend on getting https://github.com/gitsubmit/gitsubmit.github.io/pull/1 merged, but you can also just work downstream of that branch for now. I don't imagine there will be any further changes to this PR, or at least any that would cause merge conflicts.

**Comment by LeBat** [comment]
I have the html set up for this, but I need to reformat them since last I looked at it, it was set up for our flask approach. I'll get the done today and set up a pull request. Sorry about the lack of communication on this.

**Comment by shawkinsl** [comment]
ok cool, thanks!
