### ISSUE TITLE
Need "change account information" page html

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#16]
Should be able to update username, password, and email. All should happen asynchronously (AJAX + some kind of "Success!" / "Error: passwords must match!" kind of deal. Fields (except password) should be auto-populated with the current data for the user (e.g. username should contain current username, etc)

**Comment by shawkinsl** [comment]
This page should also include:

- Changing username/password/email
- Adding SSH keys

**Comment by sonph** [comment]
So let's have this a single view linked to __Account__ in the menu bar and have 2 [tabbed sections](http://materializecss.com/tabs.html) __personal information__ (name, email, username, etc.) and __account settings__ (keys, passwords, notifications settings?, etc.)

**Comment by sonph** [comment]
FYI I'm working on #71, the tabs and the account settings section. I'll leave the personal information section to you @LeBat

**Comment by sonph** [comment]
<img width="806" alt="screen shot 2015-10-23 at 1 38 15 pm" src="https://cloud.githubusercontent.com/assets/2466660/10701820/63d6d806-798b-11e5-949e-f72244eb247c.png">

**Comment by sonph** [comment]
duplicate #70
