### ISSUE TITLE
Need cool error pages (404, 500, etc)

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#28]
Inspiration: https://github.com/thispagedoesntexist

**Comment by sonph** [comment]
So what should we do with the ice cream pic?

**Comment by shawkinsl** [comment]
So I actually emailed the dean about the complete lack of response from both faculty and service accounts like "WebDeveloper@utd" (there were a few other things that I emailed him about, but I included those experiences in there as well) and he managed to get someone to respond with a "we will respond soon" email (*super* helpful).

TL:DR; still no permission but I'm pretty fed up with UTD so I vote just use it and if we get a cease and desist or whatever we can take it down.
