### ISSUE TITLE
Need API built out for login and signup

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#64]
See Functional Requirements (https://github.com/gitsubmit/gitsubmit-backend/wiki/Functional-Requirements)

# POST (only)

`api:/login/ {username: <str>, password: <str>}`

`api:/signup/ {username: <str>, password: <str>, email: <str>}`

**Comment by sonph** [comment]
A couple of things from the top of my mind on this:
- When user logs in we'll return a token associated with the session, and all subsequent requests will include this token and user name in the HTTP header
- On the backend we will have a mapping from username -> set of tokens. When we receive the requests we'll get the set of tokens and check if the token is in the set.
- Extra credits: session mgmt (user can remove a token thereby invalidate a session), expiration for tokens e.g. 1 week

**Comment by shawkinsl** [comment]
I think all these should be already solved by JWT's, which afaik have already been "implemented" in python and angular (js): http://jwt.io/

**Comment by sonph** [comment]
It says it's a cloud service so we'll have to create an account and use it for token generation and verification?

**Comment by shawkinsl** [comment]
oh whoops sorry I thought jwt.io was docs for jwt's, ignore that link then

**Comment by sonph** [comment]
No you're actually right. It's created by Auth0 and the footer is basically and ad for Auth0 cloud service. From the docs it looks like we can use [pyjwt](https://github.com/jpadilla/pyjwt)] for the backend and the frontend probably doesn't need to process it besides storing the token and send it back with every request.

**Comment by Tsintsir** [comment]
Should signup simply return a success value ("return jsonify({"result": "success"}), 200") or should it also log the user in with the provided credentials?

**Comment by Tsintsir** [comment]
55116aada02cd4306eaf0cc676aadf6e9d597188 

let me know if this commit looks ok. i'm specifically wondering if i'm getting the arguments from the form right

**Comment by sonph** [comment]
I'm not sure if we need the `.form` part since it's gonna be a POST request with a JSON body.
If you have `curl` installed you can try
`curl -H "Content-Type: application/json" -X POST -d '{"username":"foo", "password":"bar", "email": "qux"}' http://localhost:8000/signup`

**Comment by shawkinsl** [comment]
`request.form` is just where post data on a request is in flask.

**Comment by shawkinsl** [comment]
I think after singing up you should be logged in, since we're not gonna bother with email verification for now

**Comment by shawkinsl** [comment]
You are getting data from post correctly. If you want to test things quickly, you can write another Python file and run it that has:

    import requests
    requests.post(url_to_test, data={paramname1="stuff"}) #etc

Curl is also a good choice, though not available in windows afaik
