### ISSUE TITLE
Need API built out for submissions

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#66]
https://github.com/gitsubmit/gitsubmit-backend/wiki/Functional-Requirements

# POST

api:/classes/<class_name>/projects/<project_name>/make_submission {owner: <str>}

api:/<username>/submissions/<submission_name>/contributors/ {username: <str>}

# GET

api:/<username>/submissions/<submission_name>/contributors/

# DELETE

`api:/<username>/submissions/<submission_name>/contributors/<username>`

**Comment by Tsintsir** [comment]
From the docs:

>api:/<username>/submissions/<submission_name>/contributors/ {username: <str>}

>If the parent project is team based and the max team member count has not been reached, any contributor shall be able to add other contributors
>POST api:/<username>/submissions/<submission_name>/contributors/ {username: <str>}

Are these two username arguments the same or different? One comes from the URL and the other from the form of the HTTP request, right? Which one represents what?

Also, what are the differences between url_name and long_name as used in several functions in db.py?

> Do not include /'es

Is this to say no apostrophes or no forward slashes? I figure the latter but just want to be sure.

**Comment by Tsintsir** [comment]
Similarly, I assume a definition like
```
@app.route('/<username>/submissions/<submission_name>/contributors/<removed_username>', methods=['DELETE'])
def remove_contributor(username, submission_name, removed_username):
```
Is reasonable for this requirement:
>Only the project owner shall be able to remove contributors, but not themselves
>DELETE
>api:/<username>/submissions/<submission_name>/contributors/<username>

**Comment by shawkinsl** [comment]
For the contributed POST:
The username in the URL refers to the owner of the submission; the username in the post data refers to the contributor you're adding. They are not the same.

**Comment by shawkinsl** [comment]
`url_name` is a url-safe string (no spaces, any special chars encoded) that you would see in a url, and `long_name` is the string you might see written out in a browser somewhere ("you're looking at project <long_name>")
