### ISSUE TITLE
Need a user landing page

### ISSUE THREAD

**Issue by shawkinsl** [gitsubmit/gitsubmit-backend#7]
Will probably just be a list of repositories. This ticket can also be used to track the design of this view.

**Comment by shawkinsl** [comment]
Moving this ticket since it is ill-defined at the moment

**Comment by sonph** [comment]
How about I make a landing page with sections like https://www.discourse.org/, for example
GitSubmit + description -> use cases -> features -> sign up -> footer?

**Comment by shawkinsl** [comment]
Moving this again... By landing page, what I mean is the page the user gets immediately after logging in. I'd like it to look pretty much like GitHub's right-hand side navigation boxes / windows. Likely three sections:
- Classes you're enrolled in
- Projects you are assigned
- Submissions you've created / are contributing to

**Comment by sonph** [comment]
@shawkinsl @Tsintsir can we get all of the needed information in an API request? I don't see any endpoint supporting this.
