### ISSUE TITLE
Create /classes/<class_name> html view

### ISSUE THREAD

**Issue by sonph** [gitsubmit/gitsubmit-backend#72]

**Comment by shawkinsl** [comment]
![screen shot 2015-10-30 at 2 55 18 pm](https://cloud.githubusercontent.com/assets/1424566/10856533/4e219808-7f16-11e5-898e-1e13c8d9933f.png)
![screen shot 2015-10-30 at 2 55 25 pm](https://cloud.githubusercontent.com/assets/1424566/10856536/4f64fb88-7f16-11e5-8d94-55d522408bd5.png)
