### ISSUE TITLE
Create /classes/create html view

### ISSUE THREAD

**Issue by sonph** [gitsubmit/gitsubmit-backend#73]

**Comment by sonph** [comment]
@shawkinsl per the functional requirements: `POST api:/classes/ {class_name: <str>, url_name: <str>, description: <str>}` I'm assuming that `url_name` is something the user (teacher) can choose so that the class is accessible at `/classes/<url_name>`?

**Comment by shawkinsl** [comment]
Yes, I think it should be teacher configurable, but permanent.
