### ISSUE TITLE
Create /classes/<class_name>/projects/<project_name> html view

### ISSUE THREAD

**Issue by sonph** [gitsubmit/gitsubmit-backend#74]

**Comment by shawkinsl** [comment]
![screen shot 2015-10-30 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/1424566/10856553/6f0f2ec2-7f16-11e5-8b81-5990e341fc25.png)
![screen shot 2015-10-30 at 2 56 25 pm](https://cloud.githubusercontent.com/assets/1424566/10856556/70c8b9e0-7f16-11e5-94cb-69780f49bb9c.png)
