### ISSUE TITLE
Ambiguous API end point

### ISSUE THREAD

**Issue by sonph** [gitsubmit/gitsubmit-backend#79]
Per the functional requirements:
`api:/classes/<class_name>/projects/<project_name>/ {project_name: <str>, url_name: <str>, description: <str>, team_based: <bool>, max_members: <int>, due_date: <str>}`

From the POST data it looks like this end point creates a new project within a class since it has `project_name`. Shouldn't the end point be `../projects/create` instead of `../projects/<project_name>/`?

**Comment by shawkinsl** [comment]
the `create` text only applies to front-facing URL's. API URL's follow (what I believe to be) REST syntax, where to create an `element` you post to `/element/`

**Comment by sonph** [comment]
Ya then I believe it should be `POST api:/element/` and not `POST api:/element/<element_name>`
